version: "1"

services:
  # 1. Backend Express API (Free Tier Eligible)
  - type: web
    name: content-api
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/db/seed.js && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://pardhu:Tharun%402006@cluster0.wsr0mth.mongodb.net/cms_db?appName=Cluster0
      - key: JWT_SECRET
        generateValue: true

  # 2. React Frontend (Free Tier Eligible)
  - type: web
    name: content-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: content-api
          property: host
